### ISSUE TITLE
работа №12

### ISSUE THREAD

**Issue by LIZACHERNYGINA** [LIZACHERNYGINA/TYY-111-2-semestr-#2]
Здравствуйте, Антон Игоревич! Прикрепила работу №12, проверьте пожалуйста.

**Comment by FlashAnton** [comment]
Здравствуйте.

Без таблицы ASCII в тестовых примерах проверить правильность сложно.
Добавьте в отчёт таблицу ASCII.

Имена файлов в работе формируются неправильно.
Очень скромный тестовый пример взяли в работу - отработайте тот, который я подготовил для проверки работоспособности Вашей программы.

Очень много неявных конструкций в коде.
Сопроводите код и блок-схему комментариями.
По итогам правок буду принимать решение: или ставить зачёт по работе, или допускать её к защите.

**Comment by LIZACHERNYGINA** [comment]
Здравствуйте! Антон Игоревич, внесла изменения в работу, проверьте пожалуйста.

**Comment by FlashAnton** [comment]
Здравствуйте.

Я просил комментарии в блок-схеме. Они не появились. Неужели нельзя было использовать текст крупнее?
Трудно читать.

Код тоже недостаточно прокомментирован.

Вы не можете текстом рассказать как это работает?

**Comment by LIZACHERNYGINA** [comment]
Здравствуйте! Антон Игоревич, я учла замечания и исправила работу, проверьте пожалуйста.

**Comment by FlashAnton** [comment]
Здравствуйте.

И, всё же, выясняется, что Вы во всём аккуратно разобрались, но некоторое время пытались это тщательно скрывать.

**Работа зачтена, защита не требуется**
